name: React Build Workflow

on:
  push:
    branches: [ "main", "React" ]
  pull_request:
    branches: [ "main", "React" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build
        run: |
          # 动态查找包含 package.json 的目录并进入
          TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;)
          echo "Target directory found: $TARGET_DIR"
          cd "$TARGET_DIR"
          
          # 执行安装和打包
          npm install
          npm run build
